site_name: Otterdog configuration @ {{ org }}
site_description: Otterdog configuration @ {{ org }}
strict: true

site_url: https://{{ org }}.github.io/.eclipsefdn/

docs_dir: ./docs
site_dir: ./_site

theme:
  name: 'material'

markdown_extensions:
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true

plugins: []
nav: []
watch: []
